# Generated by Django 2.1.7 on 2019-03-21 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=100)),
                ('classid', models.CharField(max_length=15)),
                ('classinstructor', models.CharField(max_length=75)),
                ('classtime', models.TimeField()),
                ('classdescription', models.TextField()),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedulecomments', models.TextField()),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planner.Classes')),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=255)),
                ('studentemail', models.EmailField(max_length=255)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='studentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planner.Student'),
        ),
    ]
